---
title: "Kara Brick: CV"
runningheader: "Here to work with great people doing great things."
subtitle: "karabrick@gmail.com | 928-890-8298" # only for html output
params:
  pdf_mode:
    value: true
  cache_data:
    value: true
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/18dXN70krk-tsSFAqnhOFa-Q-03kYBT_8Nie8vJzFsig/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


```{marginfigure, echo = T}
**Key Data Highlights (linked):**
```

```{marginfigure, echo = T}
Dashboard Creation: [Shiny Dashboard](https://karabrick.shinyapps.io/BostonHomeValuesandDemographics/)
```

```{marginfigure, echo = T}
Writing Sample: [Remembering Relationships for Students](https://krbrick.github.io/writingsample.io/)
```

```{marginfigure, echo = T}
Published in 2021, with shared first authorship:  
```

```{marginfigure, echo = T}
1.[_Training-of-Trainers Neuroscience and Mental Health Teacher Education in Liberia Improves Self-Reported Support for Students_](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8249721/)    
```

```{marginfigure, echo = T}
2.[_Tiered Neuroscience and Mental Health Professional Development in Liberia Improves Teacher Self-Efficacy, Self-Responsibility, and Motivation_](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8144652/)
```


```{r}
# Note the special double pipe so we modify the CV object in place
#CV %<>% print_text_block("intro") 
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('education')
```


```{marginfigure, echo = T}
**Interested and experienced in:**   
```

```{marginfigure, echo = T}  
Antiracism training/systemic racism awareness 
[Qaulitative research methodolies](https://krbrick.github.io/)  
[Mental health social media creation](https://www.tiktok.com/@karabrick)
```

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

```{r}
#CV %<>% print_text_block('industy_experience_aside')
```

```{r}
CV %<>% print_section('industry_positions')
```


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


```{r}
#CV %<>% print_text_block('teaching_experience_aside')
```

```{r}
CV %<>% print_section('teaching_positions')
```



```{r}
#CV %<>% print_section('data_science_writings')
```


```{r}
#CV %<>% print_section('about_me_press')
```


```{r}
#CV %<>% print_section('by_me_press')
```


Selected Publications, Posters, and Talks {data-icon=book}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('academic_articles')
```

```{marginfigure, echo = T}
This CV was created using the [Tufte Package](https://github.com/rstudio/tufte), using data-driven functions created by [Nick Strayer](http://nickstrayer.me/datadrivencv/)
```

```{r}
#CV %<>% print_links()
```

```{r bib, include=FALSE}
# create a bib file for the R packages used in this document
knitr::write_bib(c('base', 'rmarkdown', 'tufte', 'datadrivencv'), file = 'skeleton.bib')
```